version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: querzel-umbrel-mosquitto_server_1
      APP_PORT: 1883

  server:
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/config:/mosquitto/config
      - ${APP_DATA_DIR}/data:/mosquitto/data
      - ${APP_DATA_DIR}/log:/mosquitto/log