version: "3.7"

services:
  server:
    image: eclipse-mosquitto
    restart: unless-stopped
    hostname: "querzel-umbrel-mosquitto_server_1"
    ports:
      # MQTT
      - 1883:1883
    volumes:
      - ${APP_DATA_DIR}/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ${APP_DATA_DIR}/data:/mosquitto/data
      - ${APP_DATA_DIR}/log:/mosquitto/log