version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: querzel-umbrel-mosquitto_server_1
      APP_PORT: 1883:1883
      PROXY_AUTH_ADD: "false"

  server:
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ${APP_DATA_DIR}/data:/mosquitto/data
      - ${APP_DATA_DIR}/log:/mosquitto/log
    environment:
      PORT: 1883