version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: querzel-umbrel-influxdb_server
      APP_PORT: 8086
      PROXY_AUTH_ADD: "false"

  influxdb:
    image: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086/tcp"
    environment:
      - TZ=Europe/Brussels
    volumes:
      - ${APP_DATA_DIR}/data/influxdb/data:/var/lib/influxdb2
      - ${APP_DATA_DIR}/data/influxdb/config:/etc/influxdb2
