version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: querzel-umbrel-influxdb_server_1
      APP_PORT: 8086
      PROXY_AUTH_ADD: "false"

  influxdb:
    image: influxdb
    restart: unless-stopped
    ports:
      - 8086:8086
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/influxdb2
      - ${APP_DATA_DIR}/config:/etc/influxdb2